#!/usr/bin/env bash
set -euo pipefail

# ------------------------------
# CONFIGURATION
# ------------------------------

# Path to your docker-compose project
PROJECT_DIR="/opt/mathenymanor/"
ENV_FILE="/opt/config/.env"

# 1Password details
VAULT_NAME="mathenymanor"
SECRETS=(
  "OPENAI"
)

# ------------------------------
# AUTHENTICATE WITH 1PASSWORD
# ------------------------------
echo "🔐 Signing in to 1Password..."
eval "$(op signin --account my.1password.com)" || {
  echo "❌ Failed to sign in to 1Password."
  exit 1
}

# ------------------------------
# BUILD .env FILE
# ------------------------------
echo "🧾 Generating .env file for docker-compose..."

# Backup existing .env if present
if [[ -f "$ENV_FILE" ]]; then
  cp "$ENV_FILE" "${ENV_FILE}.bak"
fi

# Write header
echo "# Auto-generated by deploy_with_secrets.sh" > "$ENV_FILE"

for key in "${SECRETS[@]}"; do
  echo "Fetching $key..."
  value=$(op read "op://$VAULT_NAME/$key/password" || op read "op://$VAULT_NAME/$key/credential")
  echo "$key=$value" >> "$ENV_FILE"
done

echo "✅ .env file created."

# ------------------------------
# RUN DOCKER COMPOSE
# ------------------------------
cd "$PROJECT_DIR"
echo "🚀 Starting containers..."
docker compose up -d

# ------------------------------
# CLEAN UP
# ------------------------------
echo "🧹 Cleaning up temporary .env..."
rm -f "$ENV_FILE"

echo "✅ Deployment complete."